// Code generated by acp-go-generator; DO NOT EDIT.

package acp

// NewRequestPermissionOutcomeCancelled constructs a RequestPermissionOutcome using the 'cancelled' variant.
func NewRequestPermissionOutcomeCancelled() RequestPermissionOutcome {
	return RequestPermissionOutcome{Cancelled: &RequestPermissionOutcomeCancelled{Outcome: "cancelled"}}
}

// NewRequestPermissionOutcomeSelected constructs a RequestPermissionOutcome using the 'selected' variant.
func NewRequestPermissionOutcomeSelected(optionId PermissionOptionId) RequestPermissionOutcome {
	return RequestPermissionOutcome{Selected: &RequestPermissionOutcomeSelected{
		OptionId: optionId,
		Outcome:  "selected",
	}}
}

// NewSessionConfigOptionSelect constructs a SessionConfigOption using the 'select' variant.
func NewSessionConfigOptionSelect(currentValue SessionConfigValueId, options SessionConfigSelectOptions) SessionConfigOption {
	return SessionConfigOption{Select: &SessionConfigOptionSelect{
		CurrentValue: currentValue,
		Options:      options,
		Type:         "select",
	}}
}

// NewSessionConfigOptionBoolean constructs a SessionConfigOption using the 'boolean' variant.
func NewSessionConfigOptionBoolean(currentValue bool) SessionConfigOption {
	return SessionConfigOption{Boolean: &SessionConfigOptionBoolean{
		CurrentValue: currentValue,
		Type:         "boolean",
	}}
}
