// Code generated by acp-go-generator; DO NOT EDIT.

package acp

// ProtocolVersionNumber is the ACP protocol version supported by this SDK.
const ProtocolVersionNumber = 1

// Agent method names
const (
	AgentMethodAuthenticate           = "authenticate"
	AgentMethodInitialize             = "initialize"
	AgentMethodLogout                 = "logout"
	AgentMethodSessionCancel          = "session/cancel"
	AgentMethodSessionClose           = "session/close"
	AgentMethodSessionDelete          = "session/delete"
	AgentMethodSessionList            = "session/list"
	AgentMethodSessionLoad            = "session/load"
	AgentMethodSessionNew             = "session/new"
	AgentMethodSessionPrompt          = "session/prompt"
	AgentMethodSessionResume          = "session/resume"
	AgentMethodSessionSetConfigOption = "session/set_config_option"
	AgentMethodSessionSetMode         = "session/set_mode"
)

// Client method names
const (
	ClientMethodElicitationComplete      = "elicitation/complete"
	ClientMethodElicitationCreate        = "elicitation/create"
	ClientMethodFsReadTextFile           = "fs/read_text_file"
	ClientMethodFsWriteTextFile          = "fs/write_text_file"
	ClientMethodSessionRequestPermission = "session/request_permission"
	ClientMethodSessionUpdate            = "session/update"
	ClientMethodTerminalCreate           = "terminal/create"
	ClientMethodTerminalKill             = "terminal/kill"
	ClientMethodTerminalOutput           = "terminal/output"
	ClientMethodTerminalRelease          = "terminal/release"
	ClientMethodTerminalWaitForExit      = "terminal/wait_for_exit"
)
